services:
  database:
    platform: "linux/x86_64"
    image: "mysql:latest"
    container_name: "db-mysql"
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: "yourdb"
      MYSQL_ROOT_PASSWORD: "strong_password"
    volumes:
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/data.sql"
    networks:
      - "mynet"

networks:
  mynet:
    driver: "bridge"